# -*- coding: utf-8 -*-
"""Parcial_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YUPzVUygh4DGkr6uJIAFZeR3nhk-tAmI
"""

import random
#04/05/2023 Sebastian Carrillo Jonathan Lopez Hernan londoño
# Crear lista de equipos locales y visitantes
equipos = ["Atlético Nacional", "Deportivo Cali", "Millonarios", "Junior", "América de Cali", "Independiente Medellín","Once Caldas","jaguares"]
equipos_local = equipos * 2
equipos_visitante = equipos * 2
random.shuffle(equipos_local)
random.shuffle(equipos_visitante)

# Crear lista de goles
goles_local = [random.randint(0, 5) for _ in range(len(equipos_local))]
goles_visitante = [random.randint(0, 3) for _ in range(len(equipos_visitante))]}{{}}

equipo_mas_goles = 0
puntos = 0
# Calcular cantidad de partidos por equipo
partidos_jugados = {equipo: equipos_local.count(equipo) + equipos_visitante.count(equipo) for equipo in equipos}
print("la cantidad de partidos jugados para cada equipo es",partidos_jugados)

# Calcular cantidad de partidos ganados, perdidos y empatados por equipo
partidos_ganados = {equipo: 0 for equipo in equipos}
partidos_perdidos = {equipo: 0 for equipo in equipos}
partidos_empatados = {equipo: 0 for equipo in equipos}

for i in range(len(equipos_local)):
    if goles_local[i] > goles_visitante[i]:
        partidos_ganados[equipos_local[i]] += 1
        partidos_perdidos[equipos_visitante[i]] += 1
    elif goles_local[i] < goles_visitante[i]:
        partidos_ganados[equipos_visitante[i]] += 1
        partidos_perdidos[equipos_local[i]] += 1
    else:
        partidos_empatados[equipos_local[i]] += 1
        partidos_empatados[equipos_visitante[i]] += 1
      
print("partidos ganados para cada equipo",partidos_ganados)
print("partidos perdidos por cada equipo",partidos_perdidos)
print("partidos empatados por cada euipo",partidos_empatados)

# Calcular cantidad de goles de los equipos locales y visitantes
goles_locales_totales = sum(goles_local) 
print("la cantidad de goles de los locales es",goles_locales_totales)
goles_visitantes_totales = sum(goles_visitante)
print("la cantidad de goles de los visitantes es",goles_visitantes_totales)

# Calcular cantidad total de goles de todos los partidos
goles_totales = goles_locales_totales + goles_visitantes_totales
print("la cantidad total de goles totales es:",goles_totales)

# Listado de los equipos con sus goles de local y visitante
for equipo in equipos:
    goles_local_equipo = sum([goles_local[i] for i in range(len(equipos_local)) if equipos_local[i] == equipo])
    goles_visitante_equipo = sum([goles_visitante[i] for i in range(len(equipos_visitante)) if equipos_visitante[i] == equipo])
    print(f"{equipo}: {goles_local_equipo} goles de local, {goles_visitante_equipo} goles de visitante")

# Equipo que más goles realizó
equipos_goles = {equipo: 0 for equipo in equipos}

for i in range(len(equipos_local)):
    equipos_goles[equipos_local[i]] += goles_local[i]
    equipos_goles[equipos_visitante[i]] += goles_visitante[i]

equipo_mas_goles = max(equipos_goles, key=equipos_goles.get)
print("el equipo con mas goles fue",equipo_mas_goles)

# Calcular cantidad de goles recibidos por equipo
goles_recibidos = {equipo: 0 for equipo in equipos}

for i in range(len(equipos_local)):
    goles_recibidos[equipos_local[i]] += goles_visitante[i]
    goles_recibidos[equipos_visitante[i]] += goles_local[i]
# Encontrar equipo que menos goles recibió
equipo_menos_goles_recibidos = min(goles_recibidos, key=goles_recibidos.get)
print("el equipo con menos goles resividos fue",equipo_menos_goles_recibidos)

# Leer nombre del equipo desde teclado
equipo_seleccionado = input("Ingrese el nombre del equipo: ")

# Listar partidos y marcadores del equipo seleccionadofor i, (local, visitante) in enumerate(zip(equipos_local, equipos_visitante)):
    if local == equipo_seleccionado or visitante == equipo_seleccionado:
        resultado = f"{goles_local[i]} - {goles_visitante[i]}"
        if local == equipo_seleccionado:
            print(f"Partido {i+1}: {local} (local) vs {visitante} ({resultado})")
        else:
            print(f"Partido {i+1}: {visitante} (visitante) vs {local} ({resultado})")

print("MENU")

print("elegir alguna de la opciones")
rint("1: Ver número de partidos jugados por cada equipo")
print("2: Ver número de partidos ganadospor cada equipo")
print("3: Ver número de partidos perdidos por cada equipo")
print("4: Ver número de partidos empatados por cada equipo")
print("5: Ver número de goles marcados por cada equipo local")
print("6: Ver número de goles marcados por cada equipo visitante")
print("7: Ver número total de goles marcados en todos los partidos")
print("8: Ver listado para cada equipo con sus goles de local y de visitante")
print("9: Ver equipos que más goles realizaron ")
print("10: Ver equipo que menos goles recibio")

opciones = int(input("Seleccione una opción: "))
if opciones== 1:
  print("la cantidad de partidos jugados para cada equipo es",partidos_jugados)
elif opciones ==2:
  print("partidos ganados para cada equipo",partidos_ganados)
elif opciones ==3:
  print("partidos perdidos por cada equipo",partidos_perdidos)
elif opciones ==4:
  print("partidos empatados por cada euipo",partidos_empatados)
elif opciones ==5:
  print("la cantidad de goles de los locales es",goles_locales_totales)
elif opciones ==6:
  print("la cantidad de goles de los visitantes es",goles_visitantes_totales)
elif opciones ==7:
  print("la cantidad total de goles totales es:",goles_totales)
elif opciones ==8:
  print(f"{equipo}: {goles_local_equipo} goles de local, {goles_visitante_equipo} goles de visitante")
elif opciones ==9:
  print("el equipo con mas goles fue",equipo_mas_goles)
elif opciones ==10:
  print("el equipo con menos goles resividos fue",equipo_menos_goles_recibidos)